//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountForInsuranceCompany
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> IdInsuranceCompany { get; set; }
        public Nullable<int> IdStatusAccount { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual StatusAccount StatusAccount { get; set; }
        public virtual User User { get; set; }
    }
}
