//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzerData
    {
        public int Id { get; set; }
        public Nullable<int> IdAnalyzer { get; set; }
        public Nullable<int> IdLaboratoryAssistant { get; set; }
        public Nullable<System.DateTime> DateTimeOfOrderReceipt { get; set; }
        public Nullable<int> IdOrderAndServices { get; set; }
        public Nullable<System.TimeSpan> LeadTime { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual OrderAndService OrderAndService { get; set; }
    }
}
