//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAndService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderAndService()
        {
            this.AnalyzerDatas = new HashSet<AnalyzerData>();
        }
    
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public Nullable<int> ServiceCode { get; set; }
        public string BarcodeCode { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalyzerData> AnalyzerDatas { get; set; }
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
        public virtual StatusServicesInOrder StatusServicesInOrder { get; set; }
    }
}
