//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderAndServices = new HashSet<OrderAndService>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public Nullable<int> IdStatusOrder { get; set; }
        public Nullable<System.TimeSpan> OrderCompletionTime { get; set; }

        public decimal FullPrice => decimal.Round(OrderAndServices.Sum(x => x.Service.Price), 2);
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAndService> OrderAndServices { get; set; }
    }
}
