//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.OrderAndServices = new HashSet<OrderAndService>();
        }
    
        public int Code { get; set; }
        public string ServiceName { get; set; }
        public decimal Price { get; set; }
        public int PeriodOfExecution { get; set; }
        public string InitialAVGDeviation { get; set; }
        public int AnalyzerType { get; set; }
        public string FinalAVGDeviation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAndService> OrderAndServices { get; set; }
    }
}
